### ISSUE TITLE
AssertionError in in orienteer-archetype-war

### ISSUE THREAD

**Issue by krichter722** [PhantomYdn/Orienteer#169]
During `mvn clean install` the following AssertionError occurs

    -------------------------------------------------------------------------------
    Test set: org.orienteer.archetype.simpletest.TestMyWebApplication
    -------------------------------------------------------------------------------
    Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 545.754 sec <<< FAILURE!
    testWebApplicationClass(org.orienteer.archetype.simpletest.TestMyWebApplication)  Time elapsed: 0.036 sec  <<< FAILURE!
    java.lang.AssertionError
	    at org.junit.Assert.fail(Assert.java:86)
	    at org.junit.Assert.assertTrue(Assert.java:41)
	    at org.junit.Assert.assertTrue(Assert.java:52)
	    at org.orienteer.archetype.simpletest.TestMyWebApplication.testWebApplicationClass(TestMyWebApplication.java:25)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:497)
	    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:497)
	    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)

in `testWebApplicationClass(org.orienteer.archetype.simpletest.TestMyWebApplication`.

The issue doesn't occur with PR #165, but with your partially applied version.

**Comment by PhantomYdn** [comment]
Thanks! I got that wrong...:( Now it  fixed.
